sudo: required
services:
 - docker

before_install:
 - docker build -t surendusuresh/react-test -f ./client/Dockerfile.dev ./client

script:
 - docker run -e CI=true surendusuresh/react-test npm run test

after_success:
 - docker build -t surendusuresh/multi-client ./client
 - docker build -t surendusuresh/multi-nginx ./nginx
 - docker build -t surendusuresh/multi-server ./server
 - docker build -t surendusuresh/mutli-worker ./worker

 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 - docker push surendusuresh/multi-client
 - docker push surendusuresh/multi-nginx
 - docker push surendusuresh/multi-server
 - docker push surendusuresh/multi-worker
